#!/bin/bash

set -e

script_name="install.sh"
domain=$1
orgname=$2
current_service=cagent

function eula_msg(){
  printf "
END USER LICENSE AGREEMENT
CYLERIAN PROVIDES THE CYLERIAN AGENT SOLELY ON THE TERMS AND CONDITIONS SET FORTH IN THIS AGREEMENT AND ON THE CONDITION THAT LICENSEE ACCEPTS AND COMPLIES WITH THEM. BY CLICKING THE “ACCEPT” BUTTON, ACCESSING AND/OR USING THE CYLERIAN AGENT, OR OTHER MEANS PROVIDED FOR OR INDICATING LICENSEE’S ACCEPTANCE, LICENSEE: (I) ACCEPTS THIS AGREEMENT AND AGREES THAT LICENSEE IS LEGALLY BOUND BY THE TERMS AND CONDITIONS HEREOF; AND (II) REPRESENTS AND WARRANTS THAT: (A) LICENSEE, IF A NATURAL PERSON, IS OF LEGAL AGE TO ENTER INTO A BINDING AGREEMENT; AND (B) IF LICENSEE IS A CORPORATION, LIMITED LIABILITY COMPANY, GENERAL OR LIMITED PARTNERSHIP, GOVERNMENTAL ORGANIZATION, OR OTHER LEGAL ENTITY, (1) LICENSEE HAS THE RIGHT, POWER, AND AUTHORITY TO ENTER INTO AND PERFORM THIS AGREEMENT; (2) LICENSEE HAS DULY APPROVED, BY ALL NECESSARY CORPORATE OR OTHER ENTITY ACTION, ITS EXECUTION, DELIVERY, AND PERFORMANCE OF THIS AGREEMENT; AND (3) THE PERSON EXECUTING THIS AGREEMENT ON BEHALF OF LICENSEE IS DULY AUTHORIZED TO DO SO AND THEREBY BIND LICENSEE TO THE TERMS AND CONDITIONS OF THIS AGREEMENT. IF LICENSEE DOES NOT AGREE TO THE TERMS OF THIS AGREEMENT, CYLERIAN DOES NOT AND SHALL NOT LICENSE THE CYLERIAN AGENT TO LICENSEE, AND LICENSEE SHALL NOT DOWNLOAD OR INSTALL THE CYLERIAN PLATFORM OR DOCUMENTATION.
NOTWITHSTANDING ANYTHING TO THE CONTRARY IN THIS AGREEMENT OR LICENSEE’S ACCEPTANCE OF THE TERMS AND CONDITIONS OF THIS AGREEMENT, NO LICENSE IS GRANTED (WHETHER EXPRESSLY, BY IMPLICATION, OR OTHERWISE) UNDER THIS AGREEMENT, AND THIS AGREEMENT EXPRESSLY EXCLUDES ANY RIGHT OR ENTITLEMENT, CONCERNING ANY CYLERIAN AGENT WHICH LICENSEE DID NOT OR DOES NOT ACQUIRE LAWFULLY OR WHICH IS NOT A LEGITIMATE, AUTHORIZED COPY OF CYLERIAN’S CYLERIAN AGENT.
1. Definitions.
(a) Certain Defined Terms. For purposes of this Agreement, the following terms have the following meanings (and other defined terms shall have the meanings ascribed to such terms in other Sections of this Agreement):
“Affiliate” means, with respect to any Person: (a) any Person directly or indirectly controlling, controlled by, or under common control with such Person; (b) any Person owning and controlling more than ten percent (10present) of the total combined voting equity interests of such Person; (c) any shareholder, member, partner, trustee, owner, director, officer, or manager of such Person; (d) any Person who is a director, officer, or manager of, or shareholder, member, partner, trustee, owner, or holder of more than ten percent (10present) of the total combined voting equity interests, of any Person described in the foregoing Clauses (a) through (c); (e) a Family Member of such Person; or (f) an agent of such Person or of any Persons listed in the foregoing Clauses (a) through (e).
“Authorized Users” means solely those individuals authorized to use the Cylerian Agent pursuant to the License (as defined herein) granted under this Agreement.
“Control” means the possession, direct or indirect, of the power and authority to direct or cause the direction of the management or policies of a Person, whether through the ownership of voting securities, by contract, or otherwise. The terms “controls”, “controlled by”, and “under common control with” have correlative meanings, irrespective of whether capitalized.
“Cylerian Platform” means the programs for which Licensee is purchasing the License, as expressly set forth in the Purchase Order, including the system intended to prevent, detect, respond and automate responses to security incidents, streamline information technology operations and enable analysis of large data sets of computer systems in which it is installed, developed and wholly owned by Cylerian and protected by Cylerian’s Intellectual Property Rights and including, but not limited to the Cylerian Agent (the “Agent”), which is software installed on the computer system equipment, and Cylerian’s centrally installed cloud-based platform (“Cloud”) with which the Agent is set to communicate for data transfer and analysis.
“Documentation” means user manuals, technical manuals, and any other materials provided by Cylerian, in printed, electronic, or other form, that describe the installation, operation, use, or technical specifications of the Cylerian Platform.
“Family Member” means (a) with respect to an individual, such individual’s present spouse, the lineal descendants (including natural children of and children adopted by the individual and/or its or her spouse, and the parents, brothers and sisters of any individual, as well as inter-vivos trusts or other entities for the benefit of any of the foregoing, or any other entity wholly owned by the foregoing; and (b) with respect to the estate of an individual, the personal representative, executor, or administrator of the individual, or any beneficiary of the deceased individual who was a spouse, brother or sister, or lineal ascendant or descendant (including natural and adopted children) of the deceased (or the deceased’s spouse), as well as trusts, custodians, or other entities for the benefit of any of the foregoing, or any other entity wholly owned by the foregoing.
“Intellectual Property Rights” means any and all registered and unregistered rights granted, applied for, or otherwise now or hereafter in existence under or related to any patent, copyright, trademark, trade secret, database protection, or other intellectual property rights laws, and all similar or equivalent rights or forms of protection, in any part of the world.
“Licensee” has the meaning set forth in the preamble.
“License Fees” means the license fees paid by Licensee for the license granted under this Agreement.
“Purchase Order” means the purchase order filled out and submitted by Licensee or on behalf of Licensee (such as through a Reseller), and accepted by Cylerian, for Licensee’s purchase of the License for the Cylerian Platform granted under this Agreement. The Purchase Order shall not amend or vary the terms and conditions set forth herein.
“Person” means an individual, corporation, general or limited partnership, joint venture, limited liability company, governmental authority, unincorporated organization, trust, association, or other entity.
“Reseller” means a Person that is an authorized reseller of the Cylerian Platform through written agreement with Cylerian.
“Third Party” means any Person other than Cylerian or Licensee.
(b) Interpretation.
(i) In General. For purposes of this Agreement, (A) the words “include”, “includes” and “including” shall be deemed to be followed by the words “without limitation”; (B) the word “or” is not exclusive; and (C) the words “herein”, “hereof”, “hereby”, “hereto” and “hereunder” refer to this Agreement as a whole. The definitions given for any defined terms in this Agreement shall apply equally to both the singular and plural forms of the terms defined. Headings in this Agreement are for convenience and reference only and shall not be used to interpret or construe provisions hereunder. All references in this Agreement shall be gender neutral, such that the masculine shall include the feminine and vice versa, and neutral references shall encompass both. Where applicable, the singular shall include the plural and vice versa. Unless the context otherwise requires, references herein: (D) to Sections mean the Sections of this Agreement; (E) to an agreement, instrument or other document means such agreement, instrument or other document as amended, supplemented and modified from time to time to the extent permitted by the provisions thereof; and (F) to a statute means such statute as amended from time to time and includes any successor legislation thereto and any regulations promulgated thereunder. The Purchase Order referred to herein shall be construed with, and as an integral part of, this Agreement to the same extent as if they were set forth verbatim herein.
(ii) No Presumptions. The parties have participated jointly in the negotiation and drafting of this Agreement. In the event an ambiguity or question of intent or interpretation arises, this Agreement shall be construed as if drafted jointly by the parties, and no presumption or burden of proof shall arise favoring or disfavoring any party by virtue of the authorship of any of the provisions of this Agreement. The parties hereto intend that each covenant and agreement contained herein shall have independent significance. If any party has breached any covenant or obligation contained herein in any respect, the fact that there exists another covenant or obligation relating to the same subject matter (regardless of the relative levels of specificity) which such party has not breached shall not detract from or mitigate the fact that such party is in breach of the first covenant or obligation.
2. License Grant and Scope. Subject to and conditioned upon Licensee’s timely payment of the License Fees as provided herein, and Licensee’s strict compliance with all other terms and conditions set forth in this Agreement, Cylerian hereby grants to Licensee a non-exclusive, non-transferable, non-sublicensable, limited license during the Term to use, solely by and through its Authorized Users, the Cylerian Platform and Documentation, solely as set forth in this Section 2 and subject to all conditions and limitations set forth in Section 3 or elsewhere in this Agreement (the “License”). The License grants Licensee the right, exercisable solely by and through Licensee’s Authorized Users, to:
(a) Download and install in accordance with the Documentation one (1) copy of the Cylerian Platform (whether the Agent, Cloud, or both) on each of the designated computers set forth on the Purchase Order owned or leased, and controlled by, Licensee; and
(b) Use, run, and access the Cylerian Platform as properly installed in accordance with this Agreement and the Documentation, solely as set forth in the Documentation and solely for Licensee’s internal business purposes.
The License does not include any grant or transfer to End User or Reseller or their respective Affiliates or to any other Person, of any ownership right, title, or interest, nor any security interest or other interest in or to the Cylerian Platform or any part thereof, or any Intellectual Property Rights in or to or otherwise in any respect relating to the Cylerian Platform or any part thereof.
3. Use Restrictions. Licensee shall not, and shall require its Authorized Users not to, directly or indirectly: (a) use (including make any copies of) the Cylerian Platform or Documentation beyond the scope of the License granted under Section 2 ; (b) provide any other Person, including any subcontractor, independent contractor, Affiliate, or service provider of Licensee, with access to or use of the Cylerian Platform or Documentation (unless otherwise agreed to in writing by Cylerian); (c) modify, translate, adapt, or otherwise create derivative works or improvements, whether or not patentable, of the Cylerian Platform or Documentation or any part thereof; (d) combine the Cylerian Platform or any part thereof with, or incorporate the Cylerian Platform or any part thereof in, any other programs; (e) reverse engineer, disassemble, decompile, decode, or otherwise attempt to derive or gain access to the source code of the Cylerian Platform or any part thereof; (f) remove, delete, alter, or obscure any trademarks or any copyright, trademark, patent, or other intellectual property or proprietary rights notices provided on or with the Cylerian Platform or Documentation, including any copy thereof; (g) copy the Cylerian Platform or Documentation, in whole or in part; (h) rent, lease, lend, sell, sublicense, assign, distribute, publish, transfer, or otherwise make available the Cylerian Platform, or any features or functionality of the Cylerian Platform, to any third party for any reason, whether or not over a network or on a hosted basis, including in connection with the internet or any web hosting, wide area network (WAN), virtual private network (VPN), virtualization, time-sharing, service bureau, software as a service, Cloud, or other technology or service; (i) use the Cylerian Platform or Documentation in violation of any law, regulation, or rule; or (j) use the Cylerian Platform or Documentation for purposes of competitive analysis of the Cylerian Platform, the development of a competing product or service, or any other purpose that is to Cylerian’s commercial disadvantage.
4. Responsibility for Use of Cylerian Platform. Licensee is responsible and liable for all uses of the Cylerian Platform and Documentation through access thereto provided by Licensee, directly or indirectly. Specifically, and without limiting the generality of the foregoing, Licensee is responsible and liable for all actions and failures to take required actions with respect to the Cylerian Platform and Documentation by its Authorized Users or by any other Person to whom Licensee or an Authorized User may provide access to or use of the Cylerian Platform and/or Documentation, whether such access or use is permitted by or in violation of this Agreement. End User shall defend, indemnify, and hold Cylerian, its Affiliates, and their respective owners, directors, officers, managers, employees, agents, subsidiaries, partners, successors and assigns, harmless from and against any suffered losses and damages (including reasonable attorney’s fees and court costs) incurred in connection with any third party claim arising from or attributable to End User’s use of the Cylerian Platform, other than as a result of Cylerian’s intentional or reckless misconduct.
5. Compliance Measures.
(a) The Cylerian Platform may contain technological copy protection or other security features designed to prevent unauthorized use of the Cylerian Platform, including features to protect against any use of the Cylerian Platform that is prohibited under Section 3.
Licensee shall not, and shall not attempt to, remove, disable, circumvent, or otherwise create or implement any workaround to, any such copy protection or security features.
(b) Cylerian may terminate the right of any Authorized User to access and use the Cylerian Platform immediately and without notice if: (i) Licensee revokes the Authorized User’s status as an Authorized User; (ii) an Authorized User fails to comply with any of the terms or conditions of this Agreement; (iii) Licensee defaults under or breaches any of the provisions of this Agreement; or (iv) either Cylerian or Licensee terminates the Agreement, or a Purchase Order, as applicable.
(c) On Cylerian’s written request, Licensee shall conduct a review of its and its Authorized Users use the Cylerian Platform and certify to Cylerian in a written instrument signed by an officer of Licensee that it is in full compliance with this Agreement, or, if Licensee discovers any noncompliance:
(i) Licensee shall immediately remedy such noncompliance and provide Cylerian with written notice thereof, and Licensee shall provide Cylerian with all access and assistance as Cylerian requests to further evaluate and remedy such noncompliance; and
(ii) If Licensee’s use of the Cylerian Platform exceeds the number of copies or Authorized Users permitted under the License, Cylerian shall have the remedies set forth in Section 5(e) .
(d) During the Term, Cylerian may, in Cylerian’s sole discretion, audit Licensee’s use of the Cylerian Platform to ensure Licensee’s compliance with this Agreement, provided that (i) any such audit shall be conducted on not less than five (5) days’ prior notice to Licensee; and (ii) no more than one (1) audit may be conducted in any twelve (12) month period except for good cause shown. Licensee shall fully cooperate with Cylerian’s personnel conducting such audits and provide all access requested by the Cylerian to records, systems, equipment, information, and personnel, including machine IDs, serial numbers, and related information. Cylerian may conduct audits only during Licensee’s normal business hours and in a manner that does not unreasonably interfere with Licensee’s business operations.
(e) If, in connection with any of the measures taken or implemented under this Section 5 , Cylerian determines that Licensee’s use of the Cylerian Platform exceeds or exceeded the use permitted by this Agreement, or otherwise fails to comply with this Agreement, then:
(i) Licensee shall, within five (5) days following the date of Cylerian’s written notification thereof, pay to Cylerian the retroactive License Fees for such excess use and, unless Cylerian terminates this Agreement pursuant to Section 5(e)(ii) , obtain and pay for a valid License to bring Licensee’s use into compliance with this Agreement. In determining the Licensee Fees payable pursuant to the foregoing, (A) unless Licensee can demonstrate otherwise by documentary evidence, all excess use of the Cylerian Platform shall be deemed to have commenced on the Effective Date of this Agreement or, if later, the completion date of any audit previously conducted by Cylerian hereunder, and continued uninterrupted thereafter; and (B) the rates for such licenses shall be determined without regard to any discount to which Licensee may have been entitled had such use been properly licensed prior to its commencement (or deemed commencement).
(ii) If the use exceeds or exceeded the use permitted by this Agreement by more than ten percent (10present), Cylerian shall also have the right to terminate this Agreement and the License granted hereunder, effective immediately upon written notice to Licensee. Cylerian’s remedies set forth in this Section 5(e) are cumulative and are in addition to, and not in lieu of, all other remedies the Cylerian may have at law or in equity, whether under this Agreement or otherwise.
6. Maintenance and Support.
(a) The License granted hereunder entitles Licensee to the basic Cylerian Platform maintenance and support services described in the Purchase Order. Such services may be provided by Cylerian or by a Reseller, at the discretion of Cylerian.
(b) Maintenance and support services will include provision of such updates, upgrades, bug fixes, patches, and other error corrections (collectively, “Updates”) as Cylerian makes generally available free of charge to all licensees of the Cylerian Platform then entitled to maintenance and support services. Cylerian may develop and provide Updates in its sole discretion, and Licensee agrees that Cylerian has no obligation to develop any Updates at all or for particular issues. Licensee further agrees that all Updates will be deemed Cylerian Platform, and related documentation will be deemed Documentation, all subject to all terms and conditions of this Agreement. Licensee acknowledges that Cylerian may provide Updates via download from a website designated by Cylerian and that Licensee’s receipt thereof will require an internet connection, which connection is Licensee’s sole responsibility. Cylerian has no obligation to provide Updates via any other media. Maintenance and support services do not include any new version or new release of the Cylerian Platform that Cylerian may issue as a separate or new product, and Cylerian may determine whether any issuance qualifies as a new version, new release, or Update in its sole discretion.
7. Collection and Use of Information. Licensee acknowledges that Cylerian may, directly or indirectly through the services of Third Parties, collect and store information regarding use of the Cylerian Platform and about equipment on which the Cylerian Platform is installed or through which it otherwise is accessed and used. Licensee agrees that the Cylerian Platform may use such information for any purpose related to any use of the Cylerian Platform by Licensee or on Licensee’s equipment, including but not limited to (a) improving the performance of the Cylerian Platform or developing Updates; and (b) verifying Licensee’s compliance with the terms of this Agreement and enforcing the Cylerian’s rights, including all Intellectual Property Rights in and to the Cylerian Platform.
8. Intellectual Property Rights. Licensee acknowledges and agrees that the Cylerian Platform and Documentation are provided under license, and not sold, to Licensee pursuant to this Agreement. Licensee does not and shall not acquire any ownership interest in the Cylerian Platform or Documentation under this Agreement, or any other rights thereto, other than to use the same in accordance with the License granted hereunder and subject to all terms, conditions, and restrictions under this Agreement. Cylerian shall retain its entire right, title, and interest in and to the Cylerian Platform and all Intellectual Property Rights arising out of or relating to the Cylerian Platform, except as expressly granted to Licensee in this Agreement.
Licensee shall use commercially reasonable efforts to safeguard the Cylerian Platform and all components thereof (including all copies thereof) from infringement, misappropriation, theft, misuse, or unauthorized access. Licensee shall promptly notify Cylerian in writing if Licensee becomes aware of any infringement of Cylerian’s Intellectual Property Rights in the Cylerian Platform and shall fully cooperate with Cylerian, at Cylerian’s sole expense, in any legal action taken by Cylerian to enforce its Intellectual Property Rights.
9. Payment. All License Fees are payable in advance in the manner set forth in the Purchase Order and are non-refundable, except as may be expressly set forth herein. License Fees are exclusive of all sales or gross receipts taxes, levies, and other similar charges (collectively, “Transaction Taxes”), and Licensee shall pay or reimburse Cylerian on demand for any and all Transaction Taxes imposed on or with respect to any License Fees payable hereunder, including but not limited to any and all State sales taxes and VAT statutorily required to be collected by Cylerian from Licensee. For clarity, Transaction Taxes shall not include any income taxes assessed on Cylerian’s income with respect to its receipt of License Fees hereunder. Any claim for statutory exemption by Licensee from any otherwise applicable Transaction Taxes shall be effective only after Cylerian receives all proper exemption forms and documentation from Licensee with respect to the same. All License Fees payable to Cylerian under this Agreement shall be paid by Licensee to Cylerian in full without any setoff, recoupment, counterclaim, deduction, debit or withholding for any reason (other than any deduction or withholding of tax as may be required by applicable law).
10. Term and Termination.
(a) This Agreement and the License granted hereunder shall remain in effect for the term set forth on the Purchase Order or until terminated as set forth herein (the “Term”).
(b) Licensee may terminate this Agreement by ceasing to use and destroying all copies of the Cylerian Platform and Documentation and giving written notice thereof to Cylerian.
(c) Cylerian may terminate this Agreement, (i) effective on written notice to Licensee, if Licensee fails to pay any amount when due under this Agreement, where such failure continues more than ten (10) days after Cylerian’s delivery of written notice thereof (a “Payment Failure”); or (ii) immediately on written notice to Licensee if any two (2) or more Payment Failures occur in any four (4) calendar month period;
(d) Cylerian may terminate this Agreement, effective upon written notice to Licensee, if Licensee breaches or fails to perform this Agreement or the Purchase Order and such breach or failure of performance: (i) is incapable of cure; or (ii) being capable of cure, remains uncured to Cylerian’s satisfaction for thirty (30) days after Cylerian provides written notice thereof.
(e) Cylerian may terminate this Agreement, effective immediately, if Licensee files, or has filed against it, a petition for voluntary or involuntary bankruptcy or pursuant to any other insolvency law, makes or seeks to make a general assignment for the benefit of its creditors or applies for, or consents to, the appointment of a trustee, receiver, or custodian for a substantial part of its property.
(f) Cylerian may terminate this Agreement, effective upon written notice to Licensee, in the event that Licensee does not perform any of its covenants or obligations hereunder due to Force Majeure for a period of sixty (60) days.
(g) Upon expiration or termination of this Agreement:
(i) The License and all rights granted to Licensee hereunder shall terminate immediately, and Licensee: (A) immediately shall cease using the Cylerian Platform and Documentation and cease conducting all activities with respect thereto; (B) within ten (10) days of such expiration or termination, (1) destroy and permanently erase from all computer, electronic, and intangible storage devices and systems directly or indirectly controlled by Licensee the Cylerian Platform and Documentation, including all files containing, reflecting, incorporating, or based on any of the foregoing, whether or not modified or merged into other materials; and (2) return to Cylerian (or its designated agent) located in the State of Florida, the delivery address for which Cylerian shall provide to Licensee in writing, any and all printed and other tangible materials containing, reflecting, incorporating, or based on the Cylerian Platform and Documentation, whether or not modified or merged into other materials; and (C) promptly certify to Cylerian in a written, signed instrument that Licensee has complied with the requirements set forth in this Section 10(g)(i); and
(ii) No expiration or termination of this Agreement shall affect Licensee’s obligation to pay all Licensee Fees which may have accrued and become due before such expiration or termination or shall entitle Licensee to any refund; and
(iii) The terms and conditions of Section 8 (Intellectual Property Rights), Section 9 (Payment), Section 11 (Disclaimer of Warranties), Section 12 (Limitation of Liability), and Section 15 (Miscellaneous), shall survive the expiration or termination of this Agreement, together with any obligation of a party which accrues prior to expiration or termination of this Agreement and/or which by the express terms of this Agreement requires or contemplates performance subsequent to expiration or termination.
11. Disclaimer of Warranties.
(a) DISCLAIMER. ALL SERVICES, DELIVERABLES, TECHNOLOGY, SOFTWARE, FEATURES, FUNCTIONALITY, CONTENT, IMAGE, FILE, DATABASE, DATA, INFORMATION, MANUAL, GUIDE, INSTRUCTION AND/OR MATERIALS PROVIDED BY OR THROUGH CYLERIAN OR ANY OF ITS AFFILIATES OR THIRD PARTY LICENSORS, RESELLERS, SUPPLIERS, OR CONTRACTORS UNDER OR IN CONNECTION WITH THIS AGREEMENT (EACH, AN “OFFERING”) ARE PROVIDED “AS IS” AND “AS AVAILABLE”. NEITHER CYLERIAN NOR ANY OF ITS AFFILIATES, AGENTS, REPRESENTATIVES, THIRD PARTY LICENSORS, RESELLERS, SUPPLIERS, OR CONTRACTORS, NOR ANY PERSON ON BEHALF OF ANY OF THE FOREGOING, MAKE ANY REPRESENTATION OR WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH RESPECT TO ANY OF THE OFFERINGS. TO THE MAXIMUM EXTENT PERMITTED UNDER APPLICABLE LAW, CYLERIAN, ITS AFFILIATES, AGENTS, REPRESENTATIVES, THIRD PARTY LICENSORS, RESELLERS, SUPPLIERS, AND CONTRACTORS HEREBY DISCLAIM ALL WARRANTIES, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTIES OF MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT, NON-INFRINGEMENT, OR ANY WARRANTIES ARISING OUT OF ANY COURSE OF DEALING OR USAGE OF TRADE. NEITHER CYLERIAN NOR ANY OF ITS AFFILIATES, AGENTS, REPRESENTATIVES, THIRD PARTY LICENSORS, RESELLERS, SUPPLIERS, OR CONTRACTORS, NOR ANY PERSON ON BEHALF OF ANY OF THE FOREGOING, WARRANT THAT ANY OF THE OFFERINGS WILL BE UNINTERRUPTED OR ERROR-FREE, FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS OR CODE; THAT ANY CONTENT, FILES, DATA OR OTHER MATERIALS UPLOADED TO, DOWNLOADED FROM, OR STORED, DISPLAYED OR OTHERWISE PROCESSED BY OR UTILIZING ANY OF THE OFFERINGS WILL BE TIMELY, CURRENT OR SECURE, OR WILL NOT BE LOST, CORRUPTED OR OTHERWISE DAMAGED OR IMPAIRED; OR THAT CYLERIAN OR ANY OF ITS AFFILIATES, AGENTS, REPRESENTATIVES, THIRD PARTY LICENSORS, RESELLERS, SUPPLIERS, OR CONTRACTORS WILL BE ABLE TO PREVENT DISRUPTION OF OR TO ANY OF THE OFFERINGS OR THAT THEY WILL CORRECT ANY DEFECTS.
(b) NON-CYLERIAN MATERIALS. CYLERIAN MAKES NO, AND HEREBY EXPRESSLY DISCLAIMS ANY AND ALL, REPRESENTATIONS OR WARRANTIES REGARDING ANY SOFTWARE, FIRMWARE HARDWARE, COMPUTERS, EQUIPMENT, DEVICES, MATERIALS, NETWORK, OR DATA OR ANY CONDITIONS OR CONFIGURATIONS OF ANY OF THE FOREGOING THAT ARE NOT OWNED OR DIRECTLY CONTROLLED BY CYLERIAN OR ITS AFFILIATES (COLLECTIVELY “NON-CYLERIAN MATERIALS”). UNDER NO CIRCUMSTANCE SHALL CYLERIAN OR ANY OF ITS AFFILIATES BE LIABLE FOR OR WITH RESPECT TO ANY LOSS OR DAMAGE ARISING FROM OR IN CONNECTION WITH ANY ERROR, FAULT OR TECHNICAL PROBLEM THAT IS CAUSED DIRECTLY OR INDIRECTLY BY ANY NON- CYLERIAN MATERIALS.
12. Limitation of Liability. TO THE FULLEST EXTENT PERMITTED UNDER
APPLICABLE LAW:
(a) NEITHER CYLERIAN NOR ANY OF ITS AFFILIATES, AGENTS, REPRESENTATIVES, THIRD PARTY LICENSORS, RESELLERS, SUPPLIERS, OR CONTRACTORS SHALL BE LIABLE TO LICENSEE OR OTHERWISE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE OR EXEMPLARY DAMAGES, INCLUDING, BUT NOT LIMITED TO, ANY DAMAGES FOR BODILY INJURY OR DEATH, OR DAMAGE OR INJURY TO ANY PROPERTY, LOSS OF PROFITS, GOODWILL, USE, FILES, DATA, CONTENT, BUSINESS, OPPORTUNITIES, REVENUES, ANTICIPATED SAVINGS OR OTHERWISE (EVEN IF CYLERIAN OR ANY SUCH OTHER PERSON HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND REGARDLESS OF WHETHER SUCH CLAIMS ARE BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR ANY OTHER LEGAL OR EQUITABLE THEORY WHATSOEVER) IN CONNECTION WITH ANY OF THE OFFERINGS, INCLUDING, WITHOUT LIMITATION, ANY DAMAGES ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE FOLLOWING: (I) ACCESS TO OR USE OF OR THE INABILITY TO ACCESS OR USE ANY CYLERIAN SERVICE OR ANY PART THEREOF OR OTHER OFFERINGS, OR ANY PART THEREOF; (II) THE PROVISION OF OR ANY DELAY OR FAILURE TO PROVIDE, OR ANY INTERRUPTION OF, ANY CYLERIAN SERVICE OR OTHER OFFERINGS; (III) ANY CYLERIAN SOFTWARE (WHETHER COMPRISING PART OF, OR UTILIZED IN CONNECTION WITH ANY CYLERIAN SERVICE OR OTHERWISE; OR (IV) ANY DELIVERABLE.
(b) IN THE EVENT THAT, NOTWITHSTANDING THE PROVISIONS OF THE FOREGOING SECTION 12(A), CYLERIAN (OR ANY OF ITS AGENTS, REPRESENTATIVES, CONTRACTORS, AFFILIATES OR THIRD PARTY LICENSORS, SUPPLIERS OR CONTRACTORS) ARE FOUND LIABLE TO RESELLER OR OTHERWISE, FOR DAMAGES FROM ANY CAUSE WHATSOEVER RELATED TO THIS AGREEMENT AND REGARDLESS OF THE FORM OF ACTION OR THEORY OF LIABILITY, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR ANY OTHER LEGAL OR EQUITABLE THEORY, THE AGGREGATE AMOUNT OF ALL SUCH LIABILITY SHALL BE LIMITED TO AND SHALL NOT EXCEED THE TOTAL AMOUNT OF FEES PAID OR PAYABLE TO CYLERIAN BY RESELLER UNDER THIS AGREEMENT FOR AND WITH RESPECT TO THE PARTICULAR SERVICES THAT GIVE RISE TO SUCH CLAIM, FOR THE MONTH IN WHICH THE CAUSE OF ACTION ACCRUED.
(c) LICENSEE HEREBY EXPRESSLY WAIVES ANY CLAIM THAT ANY EXCLUSIONS SET FORTH IN THIS SECTION OF THIS AGREEMENT DEPRIVE RESELLER OF AN ADEQUATE REMEDY OR CAUSE THE AGREEMENT TO FAIL OF ITS ESSENTIAL PURPOSE. LICENSEE FURTHERMORE ACKNOWLEDGES THAT AN ESSENTIAL PURPOSE OF THE EXCLUSION OF WARRANTIES AND THE LIMITATION OF LIABILITY PROVIDED IN THIS AGREEMENT IS AN ALLOCATION OF RISK BETWEEN CYLERIAN ON THE ONE HAND, AND LICENSEE ON THE OTHER, WHICH ALLOCATION OF RISK IS REFLECTED IN THE APPLICABLE FEES AND OTHER ARRANGEMENTS BETWEEN CYLERIAN AND LICENSEE IN THIS AGREEMENT AND THAT CYLERIAN WOULD NOT BE WILLING TO ENTER INTO THIS AGREEMENT WITH LICENSEE, OR TO PROVIDE LICENSEE WITH ANY CYLERIAN SERVICES OR OTHER OFFERINGS, IF CYLERIAN WERE REQUIRED TO BEAR ANY ADDITIONAL RISK. THE FOREGOING LIMITATIONS AND EXCLUSIONS APPLY TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW.
13. Export Regulation. The Cylerian Platform and Documentation may be subject to U.S. export control laws, including the Export Control Reform Act and its associated regulations. Without limiting the other terms and conditions of this Agreement: (a) Licensee shall not, directly or indirectly, export, re-export, or release the Cylerian Platform or Documentation to, or make the Cylerian Platform or Documentation accessible from, any jurisdiction or country (or to or by any Person) to which export, re-export, or release is prohibited by law, rule, or regulation; and (b) Licensee shall comply with all applicable Federal laws, regulations, and rules, and complete all required undertakings (including obtaining any necessary export license or other governmental approval), prior to exporting, re-exporting, releasing, or otherwise making the Cylerian Platform or Documentation available outside the U.S.
14. U.S. Government Rights. The Cylerian Platform is commercial computer software, as such term is defined in 48 C.F.R. §2.101. Accordingly, if Licensee is the U.S. Government or any contractor thereof, Licensee shall receive only those rights with respect to the Cylerian Platform and Documentation as are granted to all other end users under license, in accordance with (a) 48 C.F.R. §227.7201 through 48 C.F.R. §227.7204, with respect to the Department of Defense and their contractors; or (b) 48 C.F.R. §12.212, with respect to all other US Government licensees and their contractors.
15. Miscellaneous.
(a) Relationship of the Parties. The relationship between the parties is that of independent contractors. Nothing contained in this Agreement will be construed as creating any agency, partnership, joint venture, or other form of joint enterprise, employment, or fiduciary relationship between the parties, and neither party shall have authority to contract for or bind the other party in any manner whatsoever.
(b) Amendments. This Agreement may not be amended, modified, altered or supplemented other than by means of a written instrument duly executed and delivered by and on behalf of each of the parties hereto. Each party expressly waives any claim that this Agreement may be modified now or at any time in the future by any of the following means: (i) orally; (ii) by implication or any course of dealing; (iii) in a record (including electronic mail) which is not signed by both parties; or (iv) any combination of the foregoing.
(c) Governing Law. This Agreement shall be construed in accordance with, and governed in all respects by, the internal laws of the State of Florida without giving effect to any choice or conflict of law provision or rule (whether of the State of Florida or any other jurisdiction) which would cause the application of laws of any jurisdiction other than those of the State of Florida.
(d) Submission to Jurisdiction. The parties hereby agree that any suit, action or proceeding seeking to enforce, interpret, or challenge the enforceability of any provision of, or based on any matter arising out of or in connection with, this Agreement or the transactions contemplated hereby, whether in contract, tort or otherwise, shall be brought exclusively in the in the United States District Court, or in the Circuit Court of the State of Florida, in each case situated in Miami-Dade County, so long as one of such courts shall have subject-matter jurisdiction over such suit, action or proceeding, and that any cause of action arising out of this Agreement shall be deemed to have arisen from a transaction of business in the State of Florida. Each of the parties hereby unconditionally and irrevocably consents to the jurisdiction of such courts (and of the appropriate appellate courts therefrom) in any such suit, action or proceeding and unconditionally and irrevocably waives, to the fullest extent permitted by law, any objection that it may now or hereafter have to the laying of the venue of any such suit, action or proceeding in any such court or that any such suit, action or proceeding which is brought in any such court has been brought in an inconvenient form.
(e) Waiver of Jury Trial. WITH RESPECT TO ANY SUIT FOR THE ENFORCEMENT, INTERPRETATION, OR CHALLENGE TO THE ENFORCEABILITY OF THIS AGREEMENT OR THE TRANSACTIONS CONTEMPLATED HEREBY, EACH PARTY HEREBY AGREES TO THE FULLEST EXTENT PERMITTED BY LAW NOT TO ELECT A TRIAL BY JURY OF ANY ISSUE TRIABLE OF RIGHT BY JURY, AND HEREBY WAIVES ANY RIGHT TO TRIAL BY JURY FULLY TO THE EXTENT THAT ANY SUCH RIGHT SHALL NOW OR HEREAFTER EXIST WITH REGARD TO THIS AGREEMENT OR ANY CLAIM, COUNTERCLAIM, OR OTHER ACTION ARISING IN CONNECTION HEREWITH. THIS WAIVER OF RIGHT TO TRIAL BY JURY IS GIVEN KNOWINGLY AND VOLUNTARILY BY EACH PARTY AND IS INTENDED TO ENCOMPASS INDIVIDUALLY EACH INSTANCE AND EACH ISSUE AS TO WHICH THE RIGHT TO A TRIAL BY JURY OTHERWISE WOULD ACCRUE. EACH PARTY IS HEREBY AUTHORIZED TO FILE A COPY OF THIS SECTION IN ANY PROCEEDING AS CONCLUSIVE EVIDENCE OF THIS WAIVER.
(f) Attorneys’ Fees. In any suit, action, or proceeding to enforce, interpret, or challenge the enforceability of this Agreement, the prevailing party in such suit, action, or proceeding shall be entitled, in addition to all other damages to which it may be entitled, to its reasonable attorneys’ fees, court costs, and all other costs of litigation or other action, through all appeals.
(g) Severability. If any provision of this Agreement, or the application of such provision, is held invalid by a court of competent jurisdiction, the remainder of this Agreement, and the application of such provision to any Person, or circumstance other than those with respect to which it is held invalid, shall not be affected.
(h) Binding Effect; Assignment. This Agreement shall be binding upon and shall inure to the benefit of the parties and their respective heirs, executors, administrators, legal representatives, successors, each as applicable, and permitted assignees. Cylerian may assign its rights and delegate its obligation under this Agreement to any of its Affiliates (in or to any entity which acquires all, or substantially all, of the assets or voting stock of Cylerian). Licensee shall not assign any of its rights or delegate any of its obligations under this Agreement without the prior written Consent of Cylerian, which Cylerian may grant or withhold in its sole discretion.
(i) Third-Party Beneficiaries. Except for the covenants and obligations provided in Section 12 (Limitation of Liability, which shall be for the benefit of and enforceable by those Persons specified therein, this Agreement is for the sole benefit of the parties (and their respective successors and permitted assigns), and nothing herein, express or implied, is intended to or shall confer upon any other Person, any legal or equitable right, benefit or remedy of any nature whatsoever under or by reason of this Agreement.
(j) Notices. All notices, requests, consents or other communications required or permitted under this Agreement shall be in writing and shall be (as elected by the party giving such notice) actually personally delivered with written acknowledgement of receipt, or delivered via Federal Express or other international overnight courier service, signature required or otherwise with such courier’s written confirmation of delivery, to the address provided in the introductory paragraph of this Agreement or to such other address as any party may designate by written notice complying with the terms of this Section. Each such notice shall be deemed delivered on the date delivered if by personal delivery or courier service as provided herein.
(k) Non-Waiver. The failure by either party to take any action or to demand compliance with any provision of this Agreement shall not constitute, or be deemed to be, a waiver of any right or remedy of such party hereunder or otherwise at law or in equity. No waiver by either party of a default or breach or threatened default or breach of this Agreement by the other party shall be held or construed to be a waiver of any other or subsequent default or breach by such party. The failure of either party to enforce at any time any of the provisions of this Agreement, or to require at any time performance by the other party of any of the provisions hereof, shall in no way be construed to be a waiver or create an estoppel from enforcement of such provisions nor in any way to affect the validity of this Agreement or any part hereof, or the right of such party to thereafter enforce each and every such provision, or to seek relief as a result of the prior breach. No waiver of any right or remedy available to a party hereto shall be binding on that party unless it is in writing and signed by that party.
(l) Further Assurances. On a party’s reasonable request, the other party shall, at the requesting party’s sole cost and expense, execute and deliver all such documents and instruments, and take all such further actions, as may be necessary to give full effect to this Agreement.
(m) Certain Equitable Remedies. Licensee acknowledges that a breach or threatened breach by Licensee of any of its covenants and obligations under Section 8 (Intellectual Property Rights) of this Agreement would give rise to irreparable harm to Cylerian, for which monetary damages would not be an adequate remedy. Licensee agrees that, in the event of a breach or a threatened breach by Licensee of any such covenants or obligations, except as expressly provided otherwise in this Agreement, Cylerian shall be entitled, in addition to any and all other rights and remedies which may be available to it in respect of such breach, to equitable relief, including a temporary restraining order, an injunction, specific performance and any other relief that which be available from a court of competent jurisdiction (without, to the extent provided by applicable law, any requirement to post bond).
(n) Remedies Cumulative. Unless and then only to the extent otherwise expressly provided in this Agreement, the rights and remedies of the parties under this Agreement are cumulative, each party shall have all rights and remedies provided by law or in equity, and nothing in this Agreement shall be construed to prevent any party from seeking and recovering monetary or other damages sustained by such party as a result of any breach or violation of the covenants or agreements set forth in this Agreement.
(o) Force Majeure. Notwithstanding any provision of this Agreement to the contrary, neither party will be liable in any respect under any theory of liability for any delay, default or failure to perform any obligation under this Agreement otherwise, due to any cause beyond its reasonable control including acts of God, war, terrorism, riot or riots, epidemics or pandemics (whether declared by the World Health Organization or otherwise), national or international declarations of emergency, embargos, strikes or walkouts or other industrial disputes, acts of civil or military authorities, government interference, denial or delays in processing of export license application, fire, floods, earthquakes, storms, or hurricanes; fuel crises, failure or interruption of electric power, telephone, fiber optic cable or the Internet or other communication connections or service (each a “Force Majeure”). \n\n"
}

function check_args(){
    if [ -z "${domain}" ] || [ -z "${orgname}" ]; then
        echo "Script requires arguements, e.g. ${script_name} DOMAIN ORG_NAME"
        exit 2
    fi
}

function install_agent() {
    mkdir -p /opt/Cylerian
    cp -u cagent /opt/Cylerian
    cd /opt/Cylerian
    ./cagent install -d $domain --on $orgname
    cd -
}

check_args

eula_msg

read -p "Do you accept the EULA? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo
else
    echo "Install of agent aborted, user must accept EULA to proceed with install"
    exit 0
fi

install_agent

if [[ $($sudo_cmd ps --no-headers -o comm 1 2>&1) == "systemd" ]] && command -v systemctl 2>&1; then

    systemctl enable ${current_service}.service
    
    # Use systemd if systemctl binary exists and systemd is the init process
    restart_cmd="$sudo_cmd systemctl restart ${current_service}.service"
    stop_instructions="$sudo_cmd systemctl stop $current_service"
    start_instructions="$sudo_cmd systemctl start $current_service"

  elif /sbin/init --version 2>&1 | grep -q upstart; then
    
    # Try to detect Upstart, this works most of the times but still a best effort
    restart_cmd="$sudo_cmd stop $current_service || true ; sleep 2s ; $sudo_cmd start $current_service"
    stop_instructions="$sudo_cmd stop $current_service"
    start_instructions="$sudo_cmd start $current_service"
fi

eval "$restart_cmd"

printf "\033[32m  If you ever want to stop the agent, run:

      $stop_instructions

  And to run it again run:

      $start_instructions\033[0m\n\n"